// Devocionario: oraciones de siempre, en el mismo orden que el devocionario de Vatican News
// (vaticannews.va/es/oraciones). Las que son textos bíblicos o himnos con traducción
// litúrgica protegida, y las oraciones escritas por los papas recientes, se abren allá.

const VN = "https://www.vaticannews.va/es/oraciones/";

// t: título · x: texto (V./R. marcan versículo y respuesta) · note: cuándo se reza · url: se abre en Vatican News · go: lleva a otro rincón
export const ORACIONES = [
  { t: "Acordaos", x: "Acordaos, ¡oh piadosísima Virgen María!, que jamás se ha oído decir que ninguno de los que han acudido a vuestra protección, implorando vuestro auxilio y reclamando vuestro socorro, haya sido abandonado de Vos.\nAnimado con esta confianza, a Vos también acudo, oh Madre, Virgen de las vírgenes, y aunque gimiendo bajo el peso de mis pecados, me atrevo a comparecer ante vuestra presencia soberana.\nNo desechéis, oh Madre de Dios, mis humildes súplicas, antes bien, escuchadlas y acogedlas benignamente.\nAmén." },
  { t: "Acto de caridad", x: "Dios mío, te amo sobre todas las cosas y al prójimo por amor a ti, porque tú eres el sumo, infinito y perfecto Bien, digno de todo amor.\nEn este amor quiero vivir y morir.\nAmén." },
  { t: "Acto de Consagración al Corazón Inmaculado de María", note: "Escrita por el papa Francisco (25 de marzo de 2022).", url: VN + "acto-de-consagracion-al-corazon-inmaculado-de-maria.html" },
  { t: "Acto de Contrición", note: "Para pedir perdón, también antes de confesarse.", x: "Dios mío, me arrepiento de todo corazón de todos mis pecados y los aborrezco, porque al pecar, no sólo merezco las penas establecidas por ti justamente, sino principalmente porque te ofendí a ti, sumo Bien y digno de amor por encima de todas las cosas.\nPor eso propongo firmemente, con ayuda de tu gracia, no pecar más en adelante y huir de toda ocasión de pecado.\nAmén." },
  { t: "Alma de Cristo", x: "Alma de Cristo, santifícame.\nCuerpo de Cristo, sálvame.\nSangre de Cristo, embriágame.\nAgua del costado de Cristo, lávame.\nPasión de Cristo, confórtame.\n¡Oh, buen Jesús, óyeme!\nDentro de tus llagas, escóndeme.\nNo permitas que me aparte de ti.\nDel maligno enemigo, defiéndeme.\nEn la hora de mi muerte, llámame\ny mándame ir a ti,\npara que con tus santos te alabe\npor los siglos de los siglos.\nAmén." },
  { t: "Ángel de Dios", x: "Ángel de Dios, que eres mi custodio,\npues la bondad divina me ha encomendado a ti,\nilumíname, guárdame,\ndefiéndeme y gobiérname.\nAmén." },
  { t: "Ángelus", note: "Al mediodía. En el Tiempo de Pascua se reza el Regina Coeli.", x: "V. El Ángel del Señor anunció a María.\nR. Y concibió por obra del Espíritu Santo.\nDios te salve, María…\n\nV. He aquí la esclava del Señor.\nR. Hágase en mí según tu palabra.\nDios te salve, María…\n\nV. Y el Verbo se hizo carne.\nR. Y habitó entre nosotros.\nDios te salve, María…\n\nV. Ruega por nosotros, santa Madre de Dios.\nR. Para que seamos dignos de alcanzar las promesas de Cristo.\n\nOremos: Derrama, Señor, tu gracia en nuestros corazones, para que, habiendo conocido por el anuncio del Ángel la encarnación de tu Hijo Jesucristo, por su pasión y su cruz seamos llevados a la gloria de su resurrección. Por Jesucristo nuestro Señor.\nAmén." },
  { t: "Ave María", x: "Dios te salve, María, llena eres de gracia,\nel Señor es contigo.\nBendita tú eres entre todas las mujeres,\ny bendito es el fruto de tu vientre, Jesús.\nSanta María, Madre de Dios,\nruega por nosotros, pecadores,\nahora y en la hora de nuestra muerte.\nAmén." },
  { t: "Bajo tu amparo", x: "Bajo tu amparo nos acogemos, santa Madre de Dios;\nno deseches las súplicas que te dirigimos en nuestras necesidades,\nantes bien, líbranos siempre de todo peligro,\n¡oh Virgen gloriosa y bendita!\nAmén." },
  { t: "Benedictus", note: "El cántico de Zacarías (Lucas 1, 68-79). Se reza en Laudes.", url: VN + "benedictus.html" },
  { t: "Comunión espiritual", note: "Cuando no puedes comulgar, para unirte a Jesús en la Eucaristía.", x: "Creo, Jesús mío, que estás real y verdaderamente en el cielo y en el Santísimo Sacramento del altar.\nTe amo sobre todas las cosas y deseo vivamente recibirte dentro de mi alma, pero no pudiendo hacerlo ahora sacramentalmente, ven al menos espiritualmente a mi corazón.\nY como si ya te hubiese recibido, te abrazo y me uno del todo a ti.\nSeñor, no permitas que jamás me aparte de ti.\nAmén." },
  { t: "Coronilla de la Divina Misericordia", note: "Se reza con un rosario común.", x: "Al comenzar: Padre nuestro, Ave María y Credo.\n\nEn cada cuenta grande:\nPadre Eterno, te ofrezco el Cuerpo y la Sangre, el Alma y la Divinidad de tu amadísimo Hijo, nuestro Señor Jesucristo, como propiciación de nuestros pecados y los del mundo entero.\n\nEn las diez cuentas pequeñas:\nPor su dolorosa Pasión, ten misericordia de nosotros y del mundo entero.\n\nAl terminar, tres veces:\nSanto Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros y del mundo entero." },
  { t: "Credo", note: "Símbolo de los Apóstoles.", x: "Creo en Dios, Padre todopoderoso,\nCreador del cielo y de la tierra.\nCreo en Jesucristo, su único Hijo, nuestro Señor,\nque fue concebido por obra y gracia del Espíritu Santo,\nnació de Santa María Virgen,\npadeció bajo el poder de Poncio Pilato,\nfue crucificado, muerto y sepultado,\ndescendió a los infiernos,\nal tercer día resucitó de entre los muertos,\nsubió a los cielos\ny está sentado a la derecha de Dios, Padre todopoderoso.\nDesde allí ha de venir a juzgar a vivos y muertos.\nCreo en el Espíritu Santo,\nla santa Iglesia católica,\nla comunión de los santos,\nel perdón de los pecados,\nla resurrección de la carne\ny la vida eterna.\nAmén." },
  { t: "El eterno reposo", note: "Por quienes ya partieron.", x: "Dales, Señor, el descanso eterno.\nY brille para ellos la luz perpetua.\nDescansen en paz.\nAmén." },
  { t: "Gloria al Padre", x: "Gloria al Padre, y al Hijo, y al Espíritu Santo.\nComo era en el principio, ahora y siempre,\npor los siglos de los siglos.\nAmén." },
  { t: "Magnificat", note: "El cántico de María (Lucas 1, 46-55). Se reza en Vísperas.", url: VN + "magnificat.html" },
  { t: "Oración a la Sagrada Familia", note: "Escrita por el papa Francisco (Amoris laetitia).", url: VN + "oracion-a-la-sagrada-familia.html" },
  { t: "Oración a San José", note: "Del papa León XIII.", x: "A ti, bienaventurado San José, acudimos en nuestra tribulación, y después de implorar el auxilio de tu santísima Esposa, solicitamos también confiadamente tu patrocinio.\nPor aquella caridad que con la Inmaculada Virgen María, Madre de Dios, te tuvo unido, y por el paterno amor con que abrazaste al Niño Jesús, humildemente te suplicamos que vuelvas benigno los ojos a la herencia que con su Sangre adquirió Jesucristo, y con tu poder y auxilio socorras nuestras necesidades.\nProtege, oh providentísimo Custodio de la divina Familia, la escogida descendencia de Jesucristo; aleja de nosotros, oh padre amantísimo, la peste del error y del vicio.\nAsístenos propicio desde el cielo en esta lucha contra el poder de las tinieblas, y como en otro tiempo libraste de la muerte la vida amenazada del Niño Jesús, así ahora defiende a la santa Iglesia de Dios de las hostiles insidias y de toda adversidad.\nY a cada uno de nosotros protégenos con tu constante patrocinio, para que, a ejemplo tuyo y sostenidos por tu auxilio, podamos vivir y morir santamente y alcanzar en el cielo la eterna bienaventuranza.\nAmén." },
  { t: "Oración por el Papa", x: "V. Oremos por nuestro Santo Padre, el Papa.\nR. El Señor lo guarde, le dé vida, lo haga dichoso en la tierra y no lo entregue en manos de sus enemigos.\n\nPadre nuestro… Dios te salve, María…" },
  { t: "Padre nuestro", x: "Padre nuestro, que estás en el cielo,\nsantificado sea tu Nombre;\nvenga a nosotros tu reino;\nhágase tu voluntad en la tierra como en el cielo.\nDanos hoy nuestro pan de cada día;\nperdona nuestras ofensas,\ncomo también nosotros perdonamos a los que nos ofenden;\nno nos dejes caer en la tentación,\ny líbranos del mal.\nAmén." },
  { t: "Regina Coeli", note: "En el Tiempo de Pascua, en lugar del Ángelus.", x: "Reina del cielo, alégrate, aleluya.\nPorque el que mereciste llevar en tu seno, aleluya,\nha resucitado, según su palabra, aleluya.\nRuega por nosotros a Dios, aleluya.\n\nV. Gózate y alégrate, Virgen María, aleluya.\nR. Porque en verdad ha resucitado el Señor, aleluya.\n\nOremos: Oh Dios, que por la resurrección de tu Hijo, nuestro Señor Jesucristo, has llenado el mundo de alegría, concédenos, por intercesión de su Madre, la Virgen María, llegar a los gozos de la vida eterna. Por Jesucristo nuestro Señor.\nAmén." },
  { t: "Rosario", go: "rosario", note: "Puedes rezarlo paso a paso con el rosario virtual.", x: "1. Señal de la cruz y Credo.\n2. Padre nuestro, tres Ave María y Gloria.\n3. En cada uno de los cinco misterios: se anuncia el misterio, Padre nuestro, diez Ave María y Gloria.\n4. Al final, la Salve.\n\nLunes y sábado: misterios gozosos.\nMartes y viernes: misterios dolorosos.\nMiércoles y domingo: misterios gloriosos.\nJueves: misterios luminosos." },
  { t: "Salve Regina", x: "Dios te salve, Reina y Madre de misericordia,\nvida, dulzura y esperanza nuestra.\nDios te salve.\nA ti llamamos los desterrados hijos de Eva;\na ti suspiramos, gimiendo y llorando\nen este valle de lágrimas.\nEa, pues, Señora, abogada nuestra,\nvuelve a nosotros esos tus ojos misericordiosos;\ny después de este destierro muéstranos a Jesús,\nfruto bendito de tu vientre.\n¡Oh clementísima, oh piadosa, oh dulce Virgen María!\n\nV. Ruega por nosotros, santa Madre de Dios.\nR. Para que seamos dignos de alcanzar las promesas de nuestro Señor Jesucristo.\nAmén." },
  { t: "San Miguel Arcángel", x: "San Miguel Arcángel, defiéndenos en la lucha.\nSé nuestro amparo contra la perversidad y asechanzas del demonio.\nReprímale Dios, pedimos suplicantes,\ny tú, Príncipe de la milicia celestial,\narroja al infierno con el divino poder a Satanás\ny a los otros espíritus malignos\nque andan dispersos por el mundo para la perdición de las almas.\nAmén." },
  { t: "Te Deum", note: "Himno de acción de gracias. Se canta el 31 de diciembre y en las grandes fiestas.", url: VN + "te-deum.html" },
  { t: "Ven Santo Espíritu", x: "Ven, Espíritu Santo,\nllena los corazones de tus fieles\ny enciende en ellos el fuego de tu amor.\n\nV. Envía tu Espíritu y todo será creado.\nR. Y renovarás la faz de la tierra.\n\nOremos: Oh Dios, que has iluminado los corazones de tus fieles con la luz del Espíritu Santo, concédenos que, guiados por el mismo Espíritu, sintamos rectamente y gocemos siempre de su consuelo. Por Jesucristo nuestro Señor.\nAmén." },
  { t: "Veni Creator", note: "Himno al Espíritu Santo, para Pentecostés y las confirmaciones.", url: VN + "veni-creator.html" },
];
