// Banco ampliado de dinámicas (100), con el mismo formato que las dinámicas base.
// pasos: un paso por línea. Descritas con palabras propias de la pastoral.

const D = (id, title, objetivo, tags, duracion, personas, lugar, materiales, pasos, variante) =>
  ({ id: "d-" + id, builtin: true, title, objetivo, tags, duracion, personas, lugar, materiales, pasos: pasos.join("\n"), variante });

export const BANCO = [
  // ---------------------------------------------------------------- Rompehielos
  D("pelota-nombres", "La pelota de los nombres", "Aprender los nombres de todos en pocos minutos.", ["rompehielos", "acogida"], 10, "8 a 25", "ambos",
    "Una pelota blanda.",
    ["En círculo, quien lanza la pelota dice su nombre y el de quien la recibe.", "Si alguien no sabe el nombre, lo pregunta antes de lanzar.", "Después de unas vueltas, se agrega una segunda pelota para subir el ritmo."],
    "Agregar al nombre una comida favorita: «Soy Camila y me gustan las sopaipillas»."),
  D("bingo-humano", "Bingo humano", "Mezclar al grupo y descubrir cosas en común.", ["rompehielos", "conocernos"], 15, "10 a 40", "interior",
    "Cartones con 9 casillas: «toca un instrumento», «nació en otra ciudad», «tiene mascota», etc. Lápices.",
    ["Cada uno recibe un cartón.", "Busca a una persona distinta que cumpla cada casilla y anota su nombre.", "El primero en completar una línea grita «¡Bingo!».", "Se leen algunos nombres y se comenta lo que más sorprendió."],
    "Incluir casillas de fe: «se sabe el Credo», «fue a un retiro», «canta en misa»."),
  D("cambio-lugar", "Se cambian de puesto…", "Activar al grupo y descubrir afinidades.", ["rompehielos", "energizante"], 10, "10 a 30", "interior",
    "Sillas en círculo, una menos que participantes.",
    ["Quien queda al centro dice: «Se cambian de puesto los que…» (tienen hermanos, les gusta el fútbol, etc.).", "Todos los que cumplen se cambian de silla y el del centro intenta sentarse.", "Quien queda sin silla es el nuevo al centro."],
    "Al final, cada uno dice algo que descubrió de otro."),
  D("nombre-gesto", "Nombre con gesto", "Recordar nombres con alegría y movimiento.", ["rompehielos", "acogida"], 10, "6 a 25", "ambos",
    "Ninguno.",
    ["En círculo, cada uno dice su nombre acompañado de un gesto.", "Todo el grupo repite el nombre y el gesto.", "Al final, se intenta recorrer el círculo solo con los gestos."],
    "Que el gesto muestre algo que le gusta hacer."),
  D("pregunta-rapida", "Preguntas rápidas en parejas", "Conversar con muchas personas en poco tiempo.", ["rompehielos", "conocernos"], 15, "10 a 40", "interior",
    "Lista de preguntas sencillas. Un temporizador.",
    ["Se forman dos filas enfrentadas.", "El animador lee una pregunta y cada pareja conversa 1 minuto.", "Una fila avanza un puesto y se lee otra pregunta.", "Cerrar con: ¿a quién conociste mejor hoy?"],
    "Para dirigentes: preguntas sobre su llamado y su servicio."),
  D("abrazo-numeros", "Grupos de…", "Formar grupos al azar mientras se rompe el hielo.", ["rompehielos", "energizante"], 5, "12 o más", "ambos",
    "Ninguno.",
    ["Todos caminan por el espacio.", "El animador grita un número: «¡Grupos de 3!».", "Se forman los grupos lo más rápido posible.", "Al último grupo formado se le hace una pregunta divertida para presentarse."],
    "Usarla para armar los grupos de trabajo del encuentro."),
  D("me-pica", "Me pica aquí", "Aprender nombres riendo.", ["rompehielos"], 10, "8 a 20", "interior",
    "Ninguno.",
    ["En círculo, el primero dice: «Me llamo Juan y me pica aquí» (se rasca una parte).", "El siguiente repite lo del anterior y agrega lo suyo.", "Se avanza hasta completar la ronda."],
    "En grupos grandes, hacer círculos de 10."),
  D("ordenarse", "Ordenarse sin hablar", "Coordinarse como grupo y romper el hielo.", ["rompehielos", "comunicacion", "equipo"], 15, "8 a 25", "ambos",
    "Una línea en el suelo o una banca larga.",
    ["El grupo se ordena por fecha de cumpleaños sin hablar, solo con gestos.", "Luego se comprueba diciendo las fechas en voz alta.", "Se repite ordenándose por altura o por número de calzado."],
    "Hacerlo sobre una banca sin bajarse (con cuidado y en un lugar seguro)."),
  D("objeto-presenta", "El objeto que me presenta", "Presentarse de forma creativa.", ["rompehielos", "conocernos"], 20, "6 a 20", "interior",
    "Cada uno trae (o elige de su mochila) un objeto.",
    ["Cada uno muestra un objeto que dice algo de él.", "Explica en una o dos frases por qué lo eligió.", "El grupo puede hacer una pregunta."],
    "Pedir con anticipación un objeto que represente su fe."),
  D("palmas-ritmo", "El ritmo del grupo", "Concentrarse y crear juntos.", ["rompehielos", "energizante", "equipo"], 10, "8 a 30", "ambos",
    "Ninguno.",
    ["Uno inicia un ritmo con palmas y pies.", "El de al lado lo repite y agrega un sonido.", "Al final todo el círculo suena junto como una orquesta."],
    "Terminar con un canto conocido usando ese ritmo."),

  // ---------------------------------------------------------------- Conocernos
  D("linea-vida", "Mi línea de la vida", "Compartir momentos importantes de la propia historia.", ["conocernos", "reflexion"], 30, "4 a 15", "interior",
    "Hojas y lápices de colores.",
    ["Cada uno dibuja una línea con 4 o 5 momentos importantes de su vida.", "Marca con un color dónde sintió a Dios cerca.", "En parejas o tríos, comparte lo que quiera.", "Nadie está obligado a contar todo."],
    "Para aspirantes: agregar el momento en que se sintieron llamados a servir."),
  D("escudo", "Mi escudo personal", "Mirar los propios dones y sueños.", ["conocernos", "reflexion"], 30, "4 a 20", "interior",
    "Hojas con un escudo dividido en 4, lápices.",
    ["En cada cuarto del escudo se dibuja: algo que hago bien, una persona importante, un sueño y una frase que me guía.", "Se comparte en grupos pequeños.", "Se pegan los escudos en la sala."],
    "Que la frase sea un versículo de la Biblia."),
  D("quien-soy", "¿Quién es?", "Conocer detalles curiosos de cada uno.", ["conocernos", "rompehielos"], 15, "8 a 30", "interior",
    "Papelitos y una bolsa.",
    ["Cada uno escribe en secreto un dato curioso suyo y lo deja en la bolsa.", "El animador lee los papelitos uno a uno.", "El grupo adivina de quién es."],
    "Datos sobre su infancia o su primera comunión."),
  D("preguntas-cartas", "La baraja de preguntas", "Conversar con profundidad de a poco.", ["conocernos", "reflexion"], 25, "4 a 12", "interior",
    "Tarjetas con preguntas de tres niveles: livianas, medianas y profundas.",
    ["Se sacan tarjetas por turnos, empezando por las livianas.", "Quien saca responde; los demás escuchan sin interrumpir.", "Se puede pasar si una pregunta incomoda.", "Se avanza a las más profundas solo si el grupo está cómodo."],
    "Preparar tarjetas sobre el tema del encuentro."),
  D("mapa-origen", "El mapa de dónde venimos", "Valorar la historia de cada familia.", ["conocernos", "acogida"], 20, "8 a 30", "interior",
    "Un mapa de Chile grande (dibujado o impreso) y adhesivos.",
    ["Cada uno marca dónde nació él o su familia.", "Se comentan las curiosidades: ¿quién viene de más lejos?", "Cerrar: «Venimos de lugares distintos y Dios nos reunió aquí»."],
    "Incluir el país de origen de familias migrantes con especial cariño."),
  D("tres-palabras", "Tres palabras", "Presentarse en pocas palabras.", ["conocernos"], 10, "6 a 25", "interior",
    "Ninguno.",
    ["Cada uno se describe con tres palabras.", "El grupo puede preguntar por una de ellas.", "Al final, cada uno dice tres palabras sobre el grupo."],
    "Tres palabras sobre cómo llega hoy al encuentro."),
  D("foto-celular", "La foto que elijo", "Compartir algo significativo usando el celular.", ["conocernos"], 20, "4 a 15", "interior",
    "Los celulares de los participantes.",
    ["Cada uno elige una foto de su galería que le guste mucho (sin mostrar a otras personas sin su permiso).", "La muestra al grupo y cuenta por qué es especial.", "Se guarda el celular al terminar."],
    "Una foto de un lugar donde se sintió en paz."),
  D("rueda-gustos", "La rueda de los gustos", "Encontrar cosas en común.", ["conocernos", "rompehielos"], 15, "10 a 30", "ambos",
    "Ninguno.",
    ["Se forman dos círculos, uno dentro del otro, mirándose.", "El animador dice un tema (música, comida, deporte) y conversan 1 minuto.", "El círculo de afuera gira y cambia de pareja."],
    "Temas de fe: santo favorito, canción de misa preferida."),
  D("mi-nombre", "La historia de mi nombre", "Valorar la propia identidad.", ["conocernos", "acogida"], 15, "4 a 20", "interior",
    "Ninguno.",
    ["Cada uno cuenta quién eligió su nombre y por qué, si lo sabe.", "Si no lo sabe, cuenta cómo le gusta que lo llamen.", "Cerrar con Isaías 43,1: «Te he llamado por tu nombre, tú eres mío»."],
    "Investigar el santo de su nombre."),
  D("cajita", "La caja de los recuerdos", "Compartir recuerdos bonitos de la infancia.", ["conocernos"], 20, "4 a 15", "interior",
    "Una caja decorada con papelitos de temas: cumpleaños, vacaciones, colegio, abuelos…",
    ["Por turnos, cada uno saca un papelito.", "Cuenta un recuerdo bonito de ese tema.", "El grupo agradece con un aplauso."],
    "Usar temas del año del grupo para cerrar el año."),

  // ---------------------------------------------------------------- Confianza
  D("caida-confianza", "Caer en buenas manos", "Vivir la confianza en el grupo de forma segura.", ["confianza"], 15, "Grupos de 7 a 9", "interior",
    "Espacio despejado. Un guía atento.",
    ["Uno se pone al centro, rígido y con los brazos cruzados.", "Los demás, muy juntos y con las manos listas, lo reciben al dejarse caer suavemente hacia los lados.", "La caída es corta: el grupo está a pocos centímetros.", "Conversar: ¿qué te costó? ¿Quién te sostiene en la vida?"],
    "Solo con grupos que ya se conocen y siempre con un dirigente cerca."),
  D("espejo", "El espejo", "Sintonizar con el otro y prestar atención.", ["confianza", "comunicacion"], 10, "En parejas", "ambos",
    "Música suave (opcional).",
    ["En parejas, frente a frente.", "Uno hace movimientos lentos y el otro los imita como un espejo.", "Cambian de rol.", "Conversar: ¿fue más fácil guiar o seguir?"],
    "Hacerlo en silencio total con música de fondo."),
  D("guia-sonido", "Sigue mi voz", "Confiar en una voz entre muchas.", ["confianza", "comunicacion"], 20, "En parejas", "interior",
    "Pañuelos para los ojos. Espacio despejado.",
    ["En parejas, uno con los ojos vendados.", "El guía elige un sonido o palabra clave y se aleja.", "Todos los guías llaman al mismo tiempo con su sonido.", "Cada uno debe llegar hasta su guía.", "Unir con Juan 10,27: «Mis ovejas escuchan mi voz»."],
    "Usar como introducción a un tema sobre el discernimiento."),
  D("silla-ciega", "Dibujo a ciegas", "Comunicarse y confiar en las indicaciones.", ["confianza", "comunicacion"], 15, "En parejas", "interior",
    "Hojas, lápices y dibujos simples impresos.",
    ["Espalda con espalda: uno tiene un dibujo y el otro una hoja en blanco.", "El primero describe el dibujo sin decir qué es.", "El segundo dibuja según lo que escucha.", "Comparan y se ríen juntos."],
    "Repetir permitiendo que quien dibuja haga preguntas."),
  D("puente-manos", "El puente de manos", "Experimentar que el grupo me sostiene.", ["confianza", "equipo"], 15, "10 a 16", "interior",
    "Espacio despejado.",
    ["Dos filas enfrentadas se toman de los antebrazos formando un puente bajo.", "Uno camina despacio por un costado mientras el grupo levanta y baja los brazos a su paso como una ola.", "Todos pasan."],
    "Sin levantar a nadie del suelo: el gesto es simbólico."),
  D("secreto-ayuda", "El ángel secreto", "Cuidar a otro sin buscar reconocimiento.", ["confianza", "servicio"], 10, "Todo el grupo", "ambos",
    "Papelitos con los nombres.",
    ["Cada uno saca en secreto el nombre de otra persona.", "Durante el encuentro o la semana, es su «ángel»: reza por él y tiene un detalle con él.", "Al final se revela (o no) quién era el ángel de quién."],
    "Hacerla durante todo un retiro."),
  D("ojos-cerrados-circulo", "Círculo de confianza", "Sentirse acogido y cuidado.", ["confianza", "acogida"], 15, "8 a 12", "interior",
    "Ninguno.",
    ["Uno al centro con los ojos cerrados.", "Los demás, en círculo muy cercano, ponen una mano en su hombro uno a uno y le dicen una palabra de ánimo.", "Se turnan quienes quieran pasar al centro."],
    "Usar al despedir a alguien que se va del grupo."),
  D("guia-mudo", "El guía mudo", "Comunicarse más allá de las palabras.", ["confianza", "comunicacion"], 20, "En parejas", "ambos",
    "Pañuelos. Un recorrido seguro.",
    ["Uno con los ojos vendados, el otro lo guía sin hablar: solo con toques en los hombros (adelante, girar, detenerse).", "Recorren un camino sencillo.", "Cambian roles.", "Conversar: ¿cómo nos guía Dios cuando no lo escuchamos con palabras?"],
    "Acordar antes las señales entre todos."),

  // ---------------------------------------------------------------- Trabajo en equipo
  D("barco-papel", "Salvar el barco", "Resolver un problema en equipo.", ["equipo", "liderazgo"], 20, "Equipos de 6 a 10", "interior",
    "Hojas de diario en el suelo.",
    ["Cada equipo se para sobre una hoja de diario.", "Cada minuto la hoja se dobla a la mitad.", "El equipo debe seguir con todos los pies sobre el papel.", "Conversar: ¿cómo se cuidaron? ¿Quién tuvo las ideas?"],
    "Hacerlo en silencio la segunda ronda."),
  D("puzzle-equipo", "El rompecabezas compartido", "Descubrir que necesitamos al otro.", ["equipo", "comunicacion"], 20, "Equipos de 4 a 5", "interior",
    "Rompecabezas sencillos con las piezas mezcladas entre equipos.",
    ["Cada equipo recibe un rompecabezas con piezas que pertenecen a otros equipos.", "Deben completarlo pidiendo y dando piezas.", "Conversar: ¿qué pasa cuando alguien se guarda lo que otro necesita?"],
    "Unirlo con 1 Corintios 12: un cuerpo, muchos miembros."),
  D("puente-espaguetis", "La torre de fideos", "Planificar y construir en equipo.", ["equipo", "liderazgo"], 30, "Equipos de 4 a 6", "interior",
    "Por equipo: 20 fideos largos crudos, 1 metro de cinta, 1 metro de lana y un malvavisco.",
    ["En 15 minutos, cada equipo construye la torre más alta que sostenga el malvavisco arriba.", "Se miden las torres.", "Conversar: ¿planificaron o probaron sobre la marcha? ¿Qué aprendieron al fallar?"],
    "Pedir que el líder sea alguien que habitualmente no lo es."),
  D("cuerda-figura", "Figuras con la cuerda", "Coordinarse sin ver.", ["equipo", "comunicacion", "confianza"], 20, "8 a 15", "ambos",
    "Una cuerda larga atada en círculo. Pañuelos.",
    ["Todos con los ojos vendados sujetan la cuerda.", "Deben formar un cuadrado, luego un triángulo.", "Cuando creen que lo lograron, se sacan las vendas.", "Conversar: ¿quién se hizo escuchar? ¿Cómo se pusieron de acuerdo?"],
    "Permitir hablar solo a dos personas elegidas por el grupo."),
  D("orquesta", "La orquesta sin instrumentos", "Crear algo juntos donde cada uno aporta.", ["equipo", "energizante"], 15, "8 a 30", "interior",
    "Ninguno.",
    ["El grupo se divide en secciones; cada una elige un sonido con la voz o el cuerpo.", "Un director señala qué sección suena y con qué fuerza.", "Se crea una pieza musical.", "Cerrar: cada voz es necesaria para la canción."],
    "Interpretar así el estribillo de una canción del cancionero."),
  D("mision-imposible", "Misión en 10 minutos", "Repartir tareas y cumplir una meta común.", ["equipo", "liderazgo"], 20, "Equipos de 5 a 8", "ambos",
    "Lista de 10 tareas (conseguir una hoja verde, inventar un lema, cantar un coro, etc.).",
    ["Cada equipo recibe la misma lista.", "Tienen 10 minutos para cumplir el mayor número de tareas.", "Se presentan los resultados con humor.", "Conversar: ¿cómo se repartieron?"],
    "Incluir una tarea de servicio: ordenar algo de la sala."),
  D("cruzar-rio", "Cruzar el río", "Pensar juntos una solución.", ["equipo", "liderazgo"], 25, "Equipos de 6 a 10", "exterior",
    "Hojas de cartón o diario (menos que participantes) como «piedras».",
    ["Todo el equipo debe cruzar de un lado a otro pisando solo las «piedras».", "Si una piedra queda sin pie encima, se pierde.", "Se planifica y se intenta.", "Conversar: ¿qué hizo posible que pasáramos todos?"],
    "Llevar a alguien con «una dificultad» simulada (por ejemplo, un pie que no puede pisar)."),
  D("cadena-ideas", "Cadena de ideas", "Construir sobre las ideas de los demás.", ["equipo", "comunicacion"], 15, "6 a 20", "interior",
    "Papelógrafo y plumones.",
    ["Se plantea una pregunta: «¿Cómo podemos invitar a más jóvenes?».", "Cada uno agrega una idea que continúe la anterior, empezando con «Sí, y además…».", "Al final se eligen las tres mejores."],
    "Usarla para planificar una actividad real del grupo."),
  D("figuras-cuerpo", "Letras con el cuerpo", "Coordinarse con humor.", ["equipo", "energizante"], 10, "Equipos de 4 a 6", "ambos",
    "Ninguno.",
    ["El animador dice una letra o palabra corta.", "Cada equipo la forma con sus cuerpos en el suelo o de pie.", "Se toma una foto (con permiso) de cada figura."],
    "Formar la palabra ÁGAPE entre todos los equipos."),
  D("restaurant", "El restaurante", "Organizarse con roles distintos.", ["equipo", "liderazgo"], 25, "Equipos de 5 a 7", "interior",
    "Hojas, plumones y objetos de la sala.",
    ["Cada equipo inventa un restaurante: nombre, menú y quién hace qué.", "Presentan su restaurante en 2 minutos.", "Conversar: ¿qué rol tomaste? ¿Te sentiste cómodo?"],
    "Que el restaurante sirva a personas en situación de calle: ¿qué cambiaría?"),
  D("mensaje-codigo", "El mensaje en clave", "Resolver un desafío de lógica en equipo.", ["equipo", "comunicacion"], 20, "Equipos de 4 a 6", "interior",
    "Una frase bíblica escrita en un código sencillo (por ejemplo, A=1, B=2).",
    ["Cada equipo recibe la clave y el mensaje cifrado.", "Gana el primero en descifrarlo.", "Se lee la frase y se comenta en una línea."],
    "Esconder partes del mensaje en distintos lugares de la sala."),
  D("domino-humano", "El dominó humano", "Encontrar conexiones con los demás.", ["equipo", "conocernos"], 15, "10 a 30", "interior",
    "Ninguno.",
    ["Uno dice dos cosas de sí: «Me gusta el fútbol y odio madrugar».", "Se le une a un lado quien comparte una de las dos y dice otras dos.", "Se forma una cadena hasta que todos estén conectados."],
    "Cerrar el círculo: el último debe conectar con el primero."),

  // ---------------------------------------------------------------- Comunicación
  D("dibujo-dictado", "El dictado del dibujo", "Comprobar lo difícil que es comunicar bien.", ["comunicacion"], 15, "6 a 30", "interior",
    "Un dibujo de figuras geométricas. Hojas y lápices.",
    ["Uno describe el dibujo de espaldas al grupo; nadie puede preguntar.", "Todos dibujan.", "Se repite permitiendo preguntas.", "Comparar: ¿qué cambió al poder preguntar?"],
    "Conversar sobre cómo escuchamos a nuestros papás."),
  D("rumor", "El rumor", "Darse cuenta de cómo se deforman las historias.", ["comunicacion", "reflexion"], 15, "6 a 20", "interior",
    "Una historia corta con muchos detalles.",
    ["Salen cinco voluntarios de la sala.", "El animador cuenta la historia al primero, quien se la cuenta al segundo, y así.", "El grupo observa cómo cambia.", "Conversar: ¿qué hacemos con lo que escuchamos de otros?"],
    "Unir con Santiago 3: el poder de la lengua."),
  D("escucha-activa", "Te escucho de verdad", "Practicar la escucha atenta.", ["comunicacion", "acogida"], 20, "En tríos", "interior",
    "Un temporizador.",
    ["En tríos: uno cuenta algo de su semana durante 2 minutos.", "Otro escucha sin interrumpir y luego resume lo que escuchó.", "El tercero observa y comenta qué gestos ayudaron.", "Se rotan los roles."],
    "Para dirigentes: practicar cómo acoger a un joven que llega triste."),
  D("palabras-prohibidas", "Palabras prohibidas", "Expresar ideas de otra manera.", ["comunicacion", "energizante"], 15, "Equipos de 4 a 8", "interior",
    "Tarjetas con una palabra y tres palabras prohibidas.",
    ["Uno describe la palabra sin decir las prohibidas.", "Su equipo adivina en un minuto.", "Gana el equipo que adivine más."],
    "Usar palabras del Evangelio: perdón, Reino, parábola."),
  D("mimica", "Película en mímica", "Comunicarse con el cuerpo.", ["comunicacion", "energizante"], 20, "Equipos de 4 a 8", "interior",
    "Papelitos con títulos de películas o pasajes bíblicos.",
    ["Uno representa el título sin hablar.", "Su equipo adivina antes de que se acabe el tiempo.", "Se turnan los equipos."],
    "Solo pasajes bíblicos: el buen samaritano, la multiplicación de los panes."),
  D("yo-mensaje", "Decirlo sin herir", "Aprender a expresar lo que molesta con respeto.", ["comunicacion", "reflexion"], 25, "6 a 20", "interior",
    "Tarjetas con situaciones cotidianas de conflicto.",
    ["Se explica la fórmula: «Yo me siento… cuando… y me gustaría…».", "En parejas, cada uno toma una situación y la practica.", "Se comparten algunos ejemplos.", "Conversar: ¿qué cambia cuando hablo desde mí?"],
    "Situaciones del propio grupo, sin nombrar a nadie."),
  D("adivina-sentimiento", "¿Qué siento?", "Reconocer las emociones de los demás.", ["comunicacion", "conocernos"], 15, "6 a 20", "interior",
    "Tarjetas con emociones (alegría, nervios, cansancio, orgullo…).",
    ["Uno saca una tarjeta y la expresa solo con la cara y el cuerpo.", "El grupo adivina.", "Conversar: ¿nos damos cuenta de cómo están los demás?"],
    "Terminar preguntando suavemente: ¿cuál de estas sientes hoy?"),
  D("historia-grupal", "La historia de a una palabra", "Escuchar y construir juntos.", ["comunicacion", "equipo"], 10, "6 a 20", "interior",
    "Ninguno.",
    ["En círculo, se inventa una historia diciendo una palabra cada uno.", "Hay que escuchar para que tenga sentido.", "Se cuenta completa al final, entre risas."],
    "Que la historia sea sobre un joven que conoce a Jesús."),

  // ---------------------------------------------------------------- Liderazgo
  D("lider-oculto", "¿Quién dirige?", "Observar cómo influye un líder.", ["liderazgo", "energizante"], 15, "10 a 30", "interior",
    "Ninguno.",
    ["Uno sale de la sala.", "El grupo elige en secreto a un líder que hace movimientos que todos imitan.", "Quien vuelve debe descubrir quién es el líder.", "Conversar: ¿cómo se nota quién guía a un grupo?"],
    "Hablar de cómo Jesús lideraba con el ejemplo."),
  D("estilos-lider", "Tres estilos de líder", "Reconocer formas de guiar a un grupo.", ["liderazgo", "reflexion"], 30, "8 a 25", "interior",
    "Tarjetas con tres estilos: el que manda todo, el que deja hacer, el que acompaña.",
    ["Tres voluntarios dirigen la misma tarea simple (ordenar sillas) cada uno con un estilo.", "El grupo observa.", "Conversar: ¿cómo se sintieron? ¿Cuál se parece a Jesús lavando los pies?"],
    "Leer Juan 13,1-15 antes de conversar."),
  D("timon", "El timón", "Practicar dar instrucciones claras.", ["liderazgo", "comunicacion"], 20, "Equipos de 5 a 8", "ambos",
    "Pañuelos. Objetos en el suelo como meta.",
    ["El equipo, con los ojos vendados y tomados de los hombros en fila, avanza.", "Solo el último, que ve, puede guiar con toques en el hombro que se transmiten hacia adelante.", "Deben llegar a recoger un objeto.", "Conversar: ¿qué hace bueno a un guía?"],
    "Que el guía cambie a mitad de camino."),
  D("lider-servidor", "El líder que sirve", "Descubrir el liderazgo como servicio.", ["liderazgo", "servicio", "reflexion"], 25, "Cualquier grupo", "interior",
    "Una toalla, un lavatorio con agua (o solo la imagen) y la Biblia.",
    ["Leer Juan 13,1-15.", "Contemplar en silencio la imagen de Jesús lavando los pies.", "Conversar: ¿a quién me toca «lavar los pies» en mi grupo?", "Cada uno escribe un servicio concreto para esta semana."],
    "Hacer el gesto de lavar las manos unos a otros."),
  D("decision-dificil", "La decisión del grupo", "Practicar decidir en conjunto.", ["liderazgo", "equipo", "comunicacion"], 25, "Equipos de 5 a 7", "interior",
    "Un caso: el grupo tiene $50.000 y cinco ideas para usarlos.",
    ["Cada equipo debe decidir en qué usar el dinero en 10 minutos.", "Deben llegar a un acuerdo, no votar al tiro.", "Presentan su decisión y cómo llegaron a ella.", "Conversar: ¿se escuchó a todos?"],
    "Usar un caso real del grupo."),
  D("delegar", "Aprender a delegar", "Confiar tareas a otros.", ["liderazgo", "equipo"], 20, "Equipos de 4 a 6", "interior",
    "Una tarea con muchos pasos (armar un mural, preparar una dinámica).",
    ["Se nombra un coordinador que no puede hacer nada con sus manos: solo organizar.", "El equipo realiza la tarea.", "Conversar: ¿qué le costó al coordinador? ¿Qué sintió el equipo?"],
    "Rotar el coordinador cada 5 minutos."),
  D("modelos", "Mis referentes", "Reconocer a quienes nos inspiran.", ["liderazgo", "reflexion"], 20, "4 a 20", "interior",
    "Hojas y lápices.",
    ["Cada uno escribe el nombre de una persona que lo inspira y tres cualidades suyas.", "Comparte en grupos pequeños.", "Conversar: ¿cuál de esas cualidades quiero cultivar?"],
    "Incluir a un santo o santa como referente."),
  D("barco-capitan", "El capitán ordena", "Reaccionar rápido y seguir instrucciones.", ["liderazgo", "energizante"], 10, "10 a 40", "ambos",
    "Ninguno.",
    ["El capitán da órdenes: «¡Babor!» (izquierda), «¡Estribor!» (derecha), «¡Hombre al agua!» (en parejas), etc.", "Quien se equivoca ayuda al capitán a vigilar.", "Se cambia de capitán."],
    "Inventar órdenes con gestos de la misa (de pie, sentados, la paz)."),

  // ---------------------------------------------------------------- Energizantes
  D("zip-zap", "Zip, zap, boing", "Despertar al grupo y concentrarse.", ["energizante", "rompehielos"], 10, "8 a 25", "ambos",
    "Ninguno.",
    ["En círculo, se pasa un «zip» al de al lado con un gesto de manos.", "«Zap» cruza el círculo hacia cualquiera.", "«Boing» devuelve al que lo envió.", "Quien se equivoca da una vuelta corriendo y vuelve."],
    "Agregar una palabra nueva cada ronda."),
  D("pollito", "El pollito inglés", "Moverse y reír.", ["energizante"], 10, "8 a 30", "ambos",
    "Ninguno.",
    ["Uno de espaldas dice «un, dos, tres, pollito inglés» y se da vuelta.", "Los demás avanzan mientras no los mira y se congelan cuando se gira.", "Quien se mueve vuelve al inicio.", "Gana quien toca la espalda del que cuenta."],
    "Avanzar en parejas tomados de la mano."),
  D("piedra-papel-gigante", "Cachipún gigante", "Energía y trabajo en equipo.", ["energizante", "equipo"], 10, "Dos equipos", "ambos",
    "Ninguno.",
    ["Cada equipo elige en secreto piedra, papel o tijera con un gesto de todo el cuerpo.", "A la cuenta de tres, ambos equipos muestran su gesto.", "El equipo perdedor corre a su zona antes de que lo atrapen."],
    "Hacer un campeonato de cachipún individual con «hinchas»."),
  D("lluvia-sonidos", "La lluvia", "Calmar y unir al grupo después de mucha energía.", ["energizante", "oracion"], 5, "Cualquier grupo", "interior",
    "Ninguno.",
    ["El animador hace un sonido y el círculo lo imita en ola: frotar manos, chasquear dedos, palmas en las piernas, pies.", "Se sube como una tormenta y luego se baja hasta el silencio.", "En el silencio, se empieza la oración."],
    "Usarla para pasar del juego a la oración."),
  D("sardinas", "Las sardinas", "Jugar todos juntos en un espacio amplio.", ["energizante", "equipo"], 20, "8 a 25", "ambos",
    "Un lugar seguro con escondites.",
    ["Uno se esconde y todos lo buscan.", "Quien lo encuentra se esconde con él en silencio.", "El último en encontrarlos se esconde en la siguiente ronda."],
    "Jugar al atardecer en un retiro (siempre dentro de un espacio delimitado)."),
  D("congelados", "Los congelados", "Moverse y cuidarse unos a otros.", ["energizante"], 10, "10 a 40", "exterior",
    "Ninguno.",
    ["Uno o dos «congeladores» tocan a los demás, que quedan inmóviles.", "Los congelados se liberan cuando un compañero pasa bajo sus piernas o los abraza.", "Se cambian los congeladores."],
    "Conversar luego: ¿quién me «descongela» cuando estoy mal?"),
  D("conejos", "Conejos y conejeras", "Activar y reírse en grupos grandes.", ["energizante", "rompehielos"], 10, "15 a 50", "ambos",
    "Ninguno.",
    ["Tríos: dos forman una conejera con las manos arriba y uno es el conejo al medio.", "Si el animador dice «¡conejos!», los conejos cambian de conejera.", "Si dice «¡conejeras!», las conejeras buscan otro conejo.", "Si dice «¡terremoto!», todos cambian."],
    "Quien queda sin lugar dice la siguiente orden."),
  D("aguila-ratones", "Gatos y ratones", "Jugar y cuidar al más débil.", ["energizante"], 10, "12 a 30", "exterior",
    "Ninguno.",
    ["Todos en círculo tomados de las manos, un ratón dentro y un gato afuera.", "El círculo ayuda al ratón levantando y bajando los brazos.", "Cuando el gato lo atrapa, se eligen otros."],
    "Cerrar: el grupo protege al que está en peligro."),
  D("baile-congelado", "Baile congelado", "Soltarse y alegrar el ambiente.", ["energizante"], 10, "Cualquier grupo", "interior",
    "Música alegre.",
    ["Todos bailan mientras suena la música.", "Cuando se detiene, todos se congelan en una pose.", "Quien se mueve ayuda a vigilar la siguiente ronda."],
    "Usar canciones del cancionero juvenil."),
  D("tren-ciego", "El tren", "Energía, orden y risas.", ["energizante", "confianza"], 10, "Equipos de 6 a 10", "ambos",
    "Pañuelos.",
    ["Cada equipo forma un tren tomado de los hombros, todos con los ojos vendados menos el último.", "El último guía con toques: hombro derecho, izquierdo, ambos (avanzar).", "Los trenes deben recorrer la sala sin chocar."],
    "Agregar paradas donde el tren recoge objetos."),
  D("pescadores", "Los pescadores", "Correr y trabajar en cadena.", ["energizante", "equipo"], 15, "12 a 40", "exterior",
    "Un espacio delimitado.",
    ["Dos pescadores tomados de la mano forman una red.", "Cada persona atrapada se suma a la red.", "Gana el último pez libre.", "Cerrar con Mateo 4,19: «Los haré pescadores de hombres»."],
    "Hacer dos redes que compiten."),
  D("simon-dice", "Jesús dice", "Atención y reacción.", ["energizante"], 10, "Cualquier grupo", "ambos",
    "Ninguno.",
    ["El animador da órdenes; solo se cumplen las que empiezan con «Jesús dice…».", "Quien se equivoca pasa a ayudar al animador.", "Al final, recordar qué nos dice Jesús de verdad en el Evangelio."],
    "Órdenes de servicio: «Jesús dice: ayuda a alguien a sentarse»."),

  // ---------------------------------------------------------------- Oración
  D("examen-dia", "Examen del día", "Mirar el día con los ojos de Dios.", ["oracion", "reflexion"], 15, "Cualquier grupo", "interior",
    "Una vela. Música suave.",
    ["En silencio, recordar el día desde la mañana.", "Agradecer un momento bonito.", "Pedir perdón por algo que no estuvo bien.", "Pedir ayuda para mañana.", "Terminar con un Padre Nuestro."],
    "Dejarlo como hábito para la semana."),
  D("oracion-respiracion", "Rezar respirando", "Aprender a orar con calma.", ["oracion"], 10, "Cualquier grupo", "interior",
    "Ninguno.",
    ["Sentados cómodos, cerrar los ojos.", "Al inspirar, decir en el corazón: «Jesús».", "Al espirar: «en ti confío».", "Repetir varios minutos en silencio."],
    "Usar otras frases breves: «Señor, ten piedad», «Ven, Espíritu Santo»."),
  D("velas-intenciones", "Velas por las intenciones", "Presentar a Dios lo que llevamos en el corazón.", ["oracion", "cierre"], 15, "Cualquier grupo", "interior",
    "Velas pequeñas, una vela grande encendida y fósforos (con cuidado).",
    ["Cada uno enciende su vela desde la vela grande.", "La deja junto a la cruz diciendo (o no) por quién reza.", "Se termina con un canto suave."],
    "Escribir las intenciones y llevarlas a la misa del domingo."),
  D("lectio-breve", "Lectio Divina breve", "Escuchar la Palabra en cuatro pasos.", ["oracion", "reflexion"], 30, "Cualquier grupo", "interior",
    "La Biblia o el Evangelio del día.",
    ["Leer: ¿qué dice el texto?", "Meditar: ¿qué me dice a mí?", "Orar: ¿qué le digo a Dios?", "Contemplar: quedarse en silencio con Él.", "Compartir libremente."],
    "Usar el Evangelio que aparece en la Capilla de la app."),
  D("oracion-manos", "La oración de los cinco dedos", "Una manera sencilla de rezar por otros.", ["oracion"], 15, "Cualquier grupo", "interior",
    "Ninguno.",
    ["Pulgar: rezo por los más cercanos.", "Índice: por quienes enseñan y guían.", "Medio: por los que gobiernan.", "Anular: por los más débiles y enfermos.", "Meñique: por mí."],
    "Dibujar la mano y escribir un nombre en cada dedo."),
  D("rosario-vivo", "Rosario vivo", "Rezar el Rosario en comunidad de forma visible.", ["oracion", "equipo"], 30, "10 o más", "ambos",
    "Velas o globos (opcional).",
    ["Cada persona es una cuenta del rosario y se ubican en forma de rosario.", "Cada uno reza en voz alta el Ave María que le toca.", "Los que son Padre Nuestro guían cada misterio."],
    "Hacerlo en el Mes de María con flores."),
  D("cartas-dios", "Lo que Dios me diría", "Escuchar el amor de Dios por mí.", ["oracion", "reflexion"], 20, "Cualquier grupo", "interior",
    "Papel, lápices, música suave.",
    ["Leer en silencio Isaías 43,1-4.", "Cada uno escribe una carta como si Dios le escribiera: «Querido/a…».", "Es personal: nadie la lee.", "Terminar con un momento de silencio."],
    "Guardar la carta en la Biblia personal."),
  D("caminata-oracion", "Caminata de oración", "Orar en movimiento y en la creación.", ["oracion"], 30, "Cualquier grupo", "exterior",
    "Un recorrido seguro con 3 o 4 estaciones marcadas.",
    ["En silencio, el grupo camina de estación en estación.", "En cada estación hay una frase bíblica y una pregunta.", "Se detienen un minuto a pensar y siguen.", "Al final comparten una frase."],
    "En Cuaresma, hacerla como un Vía Crucis breve."),
  D("alabanza-espontanea", "Gracias por…", "Agradecer juntos.", ["oracion", "cierre"], 10, "Cualquier grupo", "interior",
    "Ninguno.",
    ["En círculo, cada uno completa en voz alta: «Señor, gracias por…».", "Después de cada acción de gracias, todos responden: «¡Te alabamos, Señor!».", "Terminar con un canto alegre."],
    "Agradecer por la persona que está a la derecha."),
  D("adoracion-guiada", "Un rato con Jesús", "Acercarse a la adoración de forma sencilla.", ["oracion"], 20, "Cualquier grupo", "interior",
    "Capilla o un lugar con una cruz y una vela. Música suave.",
    ["El guía explica que solo vamos a estar con Jesús, como con un amigo.", "Lee breves frases cada 3 o 4 minutos («Aquí estoy», «Te entrego mi semana»).", "Hay largos momentos de silencio.", "Termina con un canto suave."],
    "Coordinar con el párroco para hacerla frente al Santísimo."),

  // ---------------------------------------------------------------- Reflexión
  D("bolsa-piedras", "Las piedras de la mochila", "Reconocer lo que nos pesa y entregarlo.", ["reflexion", "oracion"], 25, "Cualquier grupo", "interior",
    "Piedras pequeñas y una mochila.",
    ["Se pasa una mochila y cada uno pone una piedra nombrando en silencio algo que le pesa.", "La mochila se pone pesada: alguien la carga un momento.", "Leer Mateo 11,28: «Vengan a mí los que están cansados».", "Se dejan las piedras a los pies de la cruz."],
    "Escribir en la piedra con plumón y llevarse una piedra «liviana» de regalo."),
  D("tiempo-vida", "Mi semana en un vaso", "Pensar en qué ocupo mi tiempo.", ["reflexion"], 20, "Cualquier grupo", "interior",
    "Un frasco, piedras grandes, piedras chicas, arena y agua.",
    ["Se intenta llenar el frasco poniendo primero la arena: no caben las piedras grandes.", "Se repite poniendo primero las piedras grandes.", "Conversar: ¿cuáles son mis «piedras grandes» (Dios, familia, amigos)? ¿Qué pongo primero?"],
    "Que cada uno escriba sus tres piedras grandes."),
  D("dilemas", "¿Qué harías tú?", "Pensar decisiones desde la fe.", ["reflexion", "comunicacion"], 30, "Equipos de 4 a 6", "interior",
    "Tarjetas con situaciones de la vida diaria (en el colegio, con amigos, en redes).",
    ["Cada equipo recibe una situación.", "Conversan qué harían y por qué.", "Presentan su respuesta y el grupo comenta.", "Cerrar: ¿qué haría Jesús en mi lugar?"],
    "Que los mismos jóvenes escriban las situaciones."),
  D("mascaras", "Mis máscaras", "Reconocer cuándo no soy auténtico.", ["reflexion", "conocernos"], 30, "Cualquier grupo", "interior",
    "Máscaras de cartulina, lápices.",
    ["Por fuera de la máscara, cada uno escribe cómo cree que lo ven los demás.", "Por dentro, cómo es de verdad o cómo se siente.", "Comparte solo lo que quiera, en parejas.", "Cerrar: Dios nos ama sin máscaras."],
    "Hacerlo en un retiro con más tiempo de silencio."),
  D("huella", "La huella que dejo", "Pensar en el bien que hacemos a otros.", ["reflexion", "servicio"], 20, "Cualquier grupo", "interior",
    "Hojas con la silueta de una huella.",
    ["Cada uno escribe dentro de la huella una huella buena que quiere dejar en su familia, colegio o grupo.", "Se pegan formando un camino en la pared.", "Leer: «Por sus frutos los conocerán» (Mt 7,16)."],
    "Revisar las huellas al final del semestre."),
  D("semillas", "La semilla", "Descubrir que crecer toma tiempo.", ["reflexion", "oracion"], 20, "Cualquier grupo", "interior",
    "Semillas, vasos con tierra, agua.",
    ["Leer la parábola del sembrador (Mc 4,1-9).", "Cada uno siembra una semilla en un vaso.", "Conversar: ¿qué tipo de tierra soy hoy?", "Cada uno se lleva su vaso para cuidarlo."],
    "Traer las plantas a un encuentro un mes después."),
  D("cartel-sueños", "El muro de los sueños", "Compartir sueños y ponerlos en manos de Dios.", ["reflexion"], 20, "Cualquier grupo", "interior",
    "Papelógrafo y notas adhesivas.",
    ["Cada uno escribe un sueño para su vida y otro para el mundo.", "Los pega en el muro.", "Se leen algunos en voz alta.", "Terminar orando: «Señor, que se haga tu voluntad»."],
    "Guardar el muro y volver a mirarlo a fin de año."),
  D("noticias", "La noticia y el Evangelio", "Mirar la realidad desde la fe.", ["reflexion", "servicio"], 30, "Equipos de 4 a 6", "interior",
    "Noticias recientes impresas (cuidando que sean adecuadas para la edad).",
    ["Cada equipo lee una noticia.", "Buscan un texto del Evangelio que ilumine esa realidad.", "Proponen un gesto concreto que podrían hacer.", "Puesta en común."],
    "Elegir noticias locales de Yungay y la región."),
  D("vaso-medio", "El vaso medio lleno", "Aprender a mirar con esperanza.", ["reflexion"], 15, "Cualquier grupo", "interior",
    "Un vaso con agua hasta la mitad.",
    ["Mostrar el vaso: ¿está medio lleno o medio vacío?", "Cada uno cuenta una situación difícil y busca algo bueno en ella.", "Cerrar con Romanos 8,28."],
    "Hacer una lista grupal de motivos de esperanza."),
  D("redes", "Lo que publico", "Pensar en cómo usamos las redes sociales.", ["reflexion", "comunicacion"], 25, "Cualquier grupo", "interior",
    "Hojas con forma de pantalla de celular.",
    ["Cada uno «diseña» una publicación que haría sentir bien a otro.", "Conversar: ¿qué publicaciones hieren? ¿Cuáles ayudan?", "Proponer un compromiso para usar las redes con cariño."],
    "Crear entre todos una publicación real para el grupo."),
  D("talentos", "Mis talentos", "Reconocer los dones recibidos.", ["reflexion", "conocernos"], 25, "Cualquier grupo", "interior",
    "Biblia (Mt 25,14-30), hojas y lápices.",
    ["Leer la parábola de los talentos.", "Cada uno escribe tres talentos que tiene.", "Los demás agregan un talento que ven en él.", "Conversar: ¿cómo los pongo al servicio de otros?"],
    "Armar un «banco de talentos» del grupo para organizar actividades."),

  // ---------------------------------------------------------------- Acogida
  D("bienvenida-tunel", "El túnel de bienvenida", "Recibir con alegría a los que llegan.", ["acogida", "energizante"], 5, "10 o más", "ambos",
    "Música alegre (opcional).",
    ["El grupo forma un túnel con los brazos en alto.", "Quien llega por primera vez pasa por el túnel entre aplausos.", "Al final se le da un abrazo o un saludo."],
    "Hacerlo al inicio del año con todos los nuevos."),
  D("padrinos", "Padrinos y madrinas", "Que nadie llegue solo al grupo.", ["acogida", "servicio"], 10, "Todo el grupo", "ambos",
    "Ninguno.",
    ["A cada joven nuevo se le asigna un «padrino» del grupo.", "El padrino lo presenta, le explica cómo funciona el encuentro y se sienta con él.", "Durante el mes, le escribe para saber cómo está."],
    "Entregar una tarjeta de bienvenida firmada por todos."),
  D("silla-vacia", "La silla vacía", "Recordar a quienes faltan.", ["acogida", "oracion"], 10, "Cualquier grupo", "interior",
    "Una silla vacía en el círculo.",
    ["Se deja una silla vacía en el círculo.", "Se nombra en voz alta a quienes no vinieron hoy.", "Se reza por ellos.", "Alguien se compromete a escribirles."],
    "Pensar a quién podríamos invitar a ocupar esa silla."),
  D("tarjeta-bienvenida", "Tarjetas de bienvenida", "Hacer sentir en casa al que llega.", ["acogida"], 15, "Cualquier grupo", "interior",
    "Cartulinas, plumones.",
    ["Cada uno escribe una frase de bienvenida y un consejo para los nuevos.", "Se entregan en el primer encuentro de los nuevos.", "Los nuevos leen algunas en voz alta."],
    "Pegarlas en un mural en la sala del grupo."),
  D("rueda-saludos", "La rueda de saludos", "Que todos se saluden por su nombre.", ["acogida", "rompehielos"], 5, "10 a 40", "ambos",
    "Ninguno.",
    ["Dos círculos concéntricos giran en sentidos contrarios.", "Al encontrarse, se saludan de una forma que dice el animador (con los codos, con una reverencia, con el nombre).", "Se repite varias veces."],
    "Terminar con el saludo de la paz."),

  // ---------------------------------------------------------------- Cierre
  D("palabra-final", "Una palabra para llevarme", "Resumir el encuentro.", ["cierre"], 5, "Cualquier grupo", "interior",
    "Ninguno.",
    ["En círculo, cada uno dice una sola palabra que resume cómo se va.", "El guía termina con una breve oración que recoja las palabras."],
    "Escribir las palabras en un papelógrafo y armar una oración."),
  D("abrazo-grupal", "El abrazo del grupo", "Terminar unidos y con cariño.", ["cierre", "acogida"], 5, "Cualquier grupo", "ambos",
    "Ninguno.",
    ["Todos en círculo, hombro con hombro, con los brazos sobre los hombros del compañero.", "Se reza un Padre Nuestro.", "Se termina con el grito del grupo."],
    "Inventar el grito o lema del grupo en el primer encuentro."),
  D("regalo-invisible", "El regalo invisible", "Despedirse deseando el bien al otro.", ["cierre", "reflexion"], 10, "6 a 20", "interior",
    "Ninguno.",
    ["Cada uno «entrega» con mímica un regalo invisible a otro y le dice qué es: «Te regalo paciencia para tus pruebas».", "Quien recibe agradece y entrega a otro.", "Todos dan y reciben."],
    "Hacerlo al final del año o de un retiro."),
  D("compromiso", "Mi compromiso de la semana", "Llevar a la vida lo vivido.", ["cierre", "servicio"], 10, "Cualquier grupo", "interior",
    "Tarjetas pequeñas, lápices.",
    ["Cada uno escribe un compromiso concreto y pequeño para la semana.", "Lo comparte (si quiere) con otra persona.", "En el próximo encuentro, se pregunta cómo les fue."],
    "Que el compañero lo llame o le escriba a mitad de semana."),
  D("bendicion-mutua", "Nos bendecimos", "Despedirse deseando la bendición de Dios.", ["cierre", "oracion"], 10, "Cualquier grupo", "interior",
    "Ninguno.",
    ["En parejas, cada uno traza una pequeña cruz en la frente del otro.", "Dice: «Que Dios te acompañe esta semana».", "Se cambian las parejas y se repite unas veces."],
    "Usarla al despedir a alguien que parte a un viaje o un servicio."),

  // ---------------------------------------------------------------- Servicio
  D("mapa-necesidades", "El mapa de las necesidades", "Descubrir dónde podemos servir.", ["servicio", "reflexion"], 30, "Equipos de 4 a 6", "interior",
    "Un plano del barrio o la parroquia dibujado en un papelógrafo.",
    ["Cada equipo marca en el mapa lugares donde hay personas que necesitan ayuda.", "Eligen uno y piensan un servicio sencillo y posible.", "Se presentan las ideas y se elige una para hacerla de verdad."],
    "Coordinar con la parroquia o Cáritas antes de realizarla."),
  D("cadena-favores", "La cadena de favores", "Hacer el bien sin esperar nada.", ["servicio"], 10, "Cualquier grupo", "ambos",
    "Tarjetas con la frase «Pásalo».",
    ["Cada uno recibe tres tarjetas.", "Durante la semana hace tres favores y deja la tarjeta para que la persona lo «pase» a otro.", "En el próximo encuentro se comparte qué pasó."],
    "Hacerlo durante el Mes de la Solidaridad."),
  D("carta-abuelos", "Cartas para los abuelos", "Llevar cariño a quienes están solos.", ["servicio", "oracion"], 30, "Cualquier grupo", "interior",
    "Papel, lápices de colores.",
    ["Cada uno escribe y decora una carta para un adulto mayor (de un hogar o de la comunidad).", "Se escriben palabras de cariño y una oración.", "Las cartas se entregan en una visita o a través de la parroquia."],
    "Organizar la visita con autorización de las familias."),
  D("servir-mesa", "Servir la mesa", "Practicar el servicio dentro del grupo.", ["servicio", "acogida"], 15, "Cualquier grupo", "interior",
    "La colación del encuentro.",
    ["Se sortean los «servidores» del día.", "Ellos sirven a los demás, preparan y ordenan.", "Los demás agradecen con un aplauso.", "Conversar: ¿cómo se sintieron sirviendo y siendo servidos?"],
    "Que los dirigentes sirvan a los jóvenes en el primer encuentro del año."),
  D("campaña", "Nuestra campaña solidaria", "Organizar una acción concreta por otros.", ["servicio", "equipo", "liderazgo"], 45, "Todo el grupo", "interior",
    "Papelógrafo y plumones.",
    ["Elegir una causa (alimentos, abrigo, útiles escolares).", "Repartir equipos: difusión, recolección, entrega.", "Fijar fechas y un responsable por equipo.", "Al terminar, evaluar y agradecer."],
    "Sumar a las familias a través de la página para familias."),
];
